"""bootstrap.propose_function_implementations — generate Python stubs for declared Functions."""
from __future__ import annotations

import textwrap
from datetime import datetime, timezone
from pathlib import Path

from agent_readiness_insights_protocol.ontology.bootstrap import (
    Proposal,
    ProposalEnvelope,
)
from agent_readiness_insights_protocol.ontology.types import Lifecycle, LifecycleState


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


_TEMPLATE_PUBLISH_ORDER = textwrap.dedent('''\
    """compute_publish_order — topological order on the dependedOnBy closure.

    Generated by bootstrap.propose_function_implementations.
    """
    from __future__ import annotations

    from pathlib import Path

    from agent_readiness.ontology.loader import load_ontology


    def compute_publish_order(changed_repo: str, ontology_root: Path | None = None) -> list[str]:
        ont = load_ontology(ontology_root or Path("ontology"))
        depended_on_by: dict[str, list[str]] = {}
        for link in ont.link_instances.get("dependsOn", []):
            frm = link.spec["from"]["id"]
            to_ = link.spec["to"]["id"]
            depended_on_by.setdefault(to_, []).append(frm)

        order: list[str] = [changed_repo]
        seen = {changed_repo}
        queue = [changed_repo]
        while queue:
            cur = queue.pop(0)
            for nxt in depended_on_by.get(cur, []):
                if nxt in seen:
                    continue
                seen.add(nxt)
                queue.append(nxt)
                order.append(nxt)
        return order
    ''')


_TEMPLATE_CHANGE_IMPACT = textwrap.dedent('''\
    """compute_change_impact — affected repos + risk per repo for a given change kind."""
    from __future__ import annotations

    from pathlib import Path

    from agent_readiness.ontology.loader import load_ontology


    _RISK_BY_KIND = {"major": "high", "minor": "medium", "patch": "low"}


    def compute_change_impact(
        changed_repo: str,
        change_kind: str,
        ontology_root: Path | None = None,
    ) -> list[dict]:
        if change_kind not in _RISK_BY_KIND:
            raise ValueError(f"Unknown change_kind: {change_kind!r}")
        risk = _RISK_BY_KIND[change_kind]
        ont = load_ontology(ontology_root or Path("ontology"))
        depended_on_by: dict[str, list[str]] = {}
        for link in ont.link_instances.get("dependsOn", []):
            depended_on_by.setdefault(link.spec["to"]["id"], []).append(link.spec["from"]["id"])

        seen = set()
        affected: list[dict] = []
        queue = list(depended_on_by.get(changed_repo, []))
        while queue:
            cur = queue.pop(0)
            if cur in seen:
                continue
            seen.add(cur)
            affected.append({"repo": cur, "risk": risk})
            queue.extend(depended_on_by.get(cur, []))
        return affected
    ''')


_TEMPLATE_DEP_GRAPH = textwrap.dedent('''\
    """compute_dep_graph — list of edges of the Repo x dependsOn graph."""
    from __future__ import annotations

    from pathlib import Path

    from agent_readiness.ontology.loader import load_ontology


    def compute_dep_graph(ontology_root: Path | None = None) -> list[dict]:
        ont = load_ontology(ontology_root or Path("ontology"))
        edges: list[dict] = []
        for link in ont.link_instances.get("dependsOn", []):
            edges.append({
                "from": link.spec["from"]["id"],
                "to": link.spec["to"]["id"],
            })
        return edges
    ''')


_TEMPLATES = {
    "compute_publish_order": _TEMPLATE_PUBLISH_ORDER,
    "compute_change_impact": _TEMPLATE_CHANGE_IMPACT,
    "compute_dep_graph": _TEMPLATE_DEP_GRAPH,
}


def propose_function_implementations(workspace: Path, function_type: str) -> ProposalEnvelope:
    if function_type not in _TEMPLATES:
        raise NotImplementedError(
            f"Unknown function_type: {function_type!r}. v1 supports: {sorted(_TEMPLATES)}"
        )
    out_dir = workspace / "ontology" / "functions"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{function_type}.py"
    out_path.write_text(_TEMPLATES[function_type])

    return ProposalEnvelope(
        tool="bootstrap.propose_function_implementations",
        target_type=function_type,
        proposed=[Proposal(
            id=function_type,
            properties={"path": str(out_path.relative_to(workspace))},
            lifecycle=Lifecycle(
                state=LifecycleState.PROPOSED,
                proposed_by="bootstrap-mcp",
                proposed_at=_now(),
                confidence=0.80,
                markers=[],
            ),
        )],
    )
