"""HTML report renderer. Requires jinja2 (optional dep)."""

from __future__ import annotations

from agent_readiness.models import Report

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Agent Readiness Report</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
    .score-badge { font-size: 3rem; font-weight: bold; }
    .score-good { color: #16a34a; }
    .score-warn { color: #ca8a04; }
    .score-bad { color: #dc2626; }
    .pillar { margin: 1.5rem 0; }
    .pillar-bar { background: #e5e7eb; border-radius: 4px; height: 12px; }
    .pillar-fill { background: #2563eb; border-radius: 4px; height: 12px; }
    .finding { margin: 0.5rem 0; padding: 0.5rem; border-left: 3px solid; }
    .finding-error { border-color: #dc2626; background: #fef2f2; }
    .finding-warn { border-color: #ca8a04; background: #fefce8; }
    .finding-info { border-color: #2563eb; background: #eff6ff; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 0.5rem; text-align: left; border-bottom: 1px solid #e5e7eb; }
  </style>
</head>
<body>
  <h1>AI Readiness Report</h1>
  <p><strong>Repository:</strong> {{ report.repo_path }}</p>
  <div class="score-badge {{ 'score-good' if report.overall_score >= 80 else 'score-warn' if report.overall_score >= 60 else 'score-bad' }}">
    {{ "%.1f"|format(report.overall_score) }} / 100
  </div>
  {% if report.safety_cap_applied %}
  <p style="color:#dc2626">&#x26A0; Safety cap applied: score reduced by {{ report.safety_cap_applied }}</p>
  {% endif %}
  <h2>Pillar Scores</h2>
  {% for ps in report.pillar_scores %}
  <div class="pillar">
    <strong>{{ ps.pillar.value.replace("_", " ").title() }}</strong>: {{ "%.1f"|format(ps.score) }}
    <div class="pillar-bar"><div class="pillar-fill" style="width:{{ ps.score }}%"></div></div>
    {% for cr in ps.check_results %}
    {% if not cr.not_measured %}
    <div style="margin-left:1rem; margin-top:0.25rem">
      <code>{{ cr.check_id }}</code>: {{ "%.0f"|format(cr.score) }}
      {% for f in cr.findings %}
      {% if f.severity.value != "info" %}
      <div class="finding finding-{{ f.severity.value }}">
        {{ f.message }}{% if f.fix_hint %} &mdash; <em>{{ f.fix_hint }}</em>{% endif %}
      </div>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    {% endfor %}
  </div>
  {% endfor %}
  <footer style="margin-top:2rem; color:#6b7280; font-size:0.875rem">
    Generated by <a href="https://github.com/your-org/agent-readiness">agent-readiness</a>
  </footer>
</body>
</html>"""


def render(report: Report) -> str:
    try:
        from jinja2 import Environment
    except ImportError as exc:
        raise ImportError(
            "HTML report requires jinja2. Install with: pip install jinja2"
        ) from exc
    env = Environment(autoescape=True)
    tmpl = env.from_string(_TEMPLATE)
    return tmpl.render(report=report)
